keys:
  - &tristan 85974506EC695392044308059D98CDACFF04FD78
  - &vpn b6439acbaeedcee31bb9ec14d2c61110c0a4eb08
creation_rules:
  - path_regex: secrets/vpn.yaml$
    key_groups:
      - pgp:
        - *tristan
        - *vpn
