keys:
  - &tristan 85974506EC695392044308059D98CDACFF04FD78
  - &proxmox f5d93389fe37e417ecb9ec8e3b2d198f7a0b474a
creation_rules:
  - path_regex: secrets/proxmox.yaml$
    key_groups:
      - pgp:
        - *tristan
        - *proxmox
